apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-cfg
data:
  db_port: "3306"
  db_name: "jumpserver"
  db_user: "jumpserver"
  db_password: "nu4x599Wq7u0Bn8EABh3J91G"
  db_host: "jumpserver-mysql"

  redis_host: "jumpserver-redis"
  redis_port: "6379"
  redis_password: "8URXPL2x3HZMi7xoGTdk3Upj"

  secret_key: "B3f2w8P2PfxIAS7s4URrD9YmSbtqX4vXdPUL217kL9XPUOWrmy"
  bootstrap_token: "7Q11Vz6R2J6BLAdO"
