apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-core
  labels:
    app.kubernetes.io/name: core
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: core
  strategy:
    rollingUpdate:    # 滚动更新
      maxSurge: 25%   # 指定可以超过期望的pod数量的最大百分比，也可以是个数
      maxUnavailable: 25%    # 指定升级过程中不可用Pod的最大数量
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core
    spec:
      containers:
      - name: jms-core
        image: wojiushixiaobai/jms_core:1.5.6
        ports:
        - containerPort: 8080
          name: core
          protocol: TCP
        - containerPort: 8070
          name: core8070
          protocol: TCP
        volumeMounts:
        - name: static
          mountPath: /opt/jumpserver/data/static
        - name: media
          mountPath: /opt/jumpserver/data/media
        env:
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_port
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_host
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_password

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_host
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_password
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_port

        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: secret_key
        - name: BOOTSTRAP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: bootstrap_token
      volumes:
      - name: static
        nfs:
          path: /data/core/static
          server: 192.168.238.100
      - name: media
        nfs:
          path: /data/core/media
          server: 192.168.238.100 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: core
  name: core
spec:
  clusterIP: None
  ports:
  - name: core
    port: 8080
    protocol: TCP
    targetPort: core
  - name: core8070
    port: 8070
    targetPort: core8070
  selector:
    app.kubernetes.io/name: core
  sessionAffinity: ClientIP
