apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-guacamole
  labels:
    app.kubernetes.io/name: guacamole
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacamole
    spec:
      containers:
      - name: jms-guacamole
        image: wojiushixiaobai/jms_guacamole:1.5.6
        ports:
        - containerPort: 8080
          name: guacamole
          protocol: TCP
        volumeMounts:
        - name: guacamole
          mountPath: /config/guacamole/keys
        env:
        - name: JUMPSERVER_SERVER
          value: http://core:8080
        - name: JUMPSERVER_KEY_DIR
          value: /config/guacamole/keys
        - name: GUACAMOLE_HOME
          value: /config/guacamole
        - name: GUACAMOLE_LOG_LEVEL
          value: ERROR
        - name: JUMPSERVER_ENABLE_DRIVE
          value: "true"
        - name: BOOTSTRAP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: bootstrap_token
      volumes:
      - name: guacamole
        nfs:
          path: /data/guacamole
          server: 192.168.238.100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: guacamole
  name: guacamole
spec:
  clusterIP: None
  ports:
  - name: guacamole
    port: 8080
    protocol: TCP
    targetPort: guacamole
  selector:
    app.kubernetes.io/name: guacamole
  sessionAffinity: ClientIP
