apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-koko
  labels:
    app.kubernetes.io/name: koko
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: koko
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: koko
    spec:
      containers:
      - name: jms-koko
        image: wojiushixiaobai/jms_koko:1.5.6
        ports:
        - containerPort: 2222
          name: koko
          protocol: TCP
        - containerPort: 5000
          name: koko5000
          protocol: TCP

        volumeMounts:
        - name: koko
          mountPath: /opt/koko/data/keys
        env:
        - name: CORE_HOST
          value: http://core:8080
        - name: BOOTSTRAP_TOKEN
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: bootstrap_token
      volumes:
      - name: koko
        nfs:
          path: /data/koko
          server: 192.168.238.100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: koko
  name: koko
spec:
 # clusterIP: None
  type: NodePort
  ports:
  - name: koko
    port: 2222
    protocol: TCP
    targetPort: koko
    nodePort: 32222
  - name: koko5000
    port: 5000
    protocol: TCP
    targetPort: koko5000
  selector:
    app.kubernetes.io/name: koko
  sessionAffinity: ClientIP
