apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  strategy:
    rollingUpdate:    # 滚动更新
      maxSurge: 25%   # 指定可以超过期望的pod数量的最大百分比，也可以是个数
      maxUnavailable: 25%    # 指定升级过程中不可用Pod的最大数量
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - name: jms-mysql
        image: wojiushixiaobai/jms_mysql:1.5.6
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_port
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_name
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: db_password
      volumes:
      - name: mysql
        nfs:
          path: /data/mysql
          server: 192.168.238.100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysql
  name: jumpserver-mysql
spec:
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/name: mysql
  sessionAffinity: ClientIP
