apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: jms-nginx
        image: wojiushixiaobai/jms_nginx:1.5.6
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        volumeMounts:
        - name: static
          mountPath: /opt/jumpserver/data/static
        - name: media
          mountPath: /opt/jumpserver/data/media
      volumes:
      - name: static
        nfs:
          path: /data/core/static
          server: 192.168.238.100
      - name: media
        nfs:
          path: /data/core/media
          server: 192.168.238.100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: jumpserver-nginx
spec:
  #clusterIP: None
  type: NodePort
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: nginx
    nodePort: 30080
  selector:
    app.kubernetes.io/name: nginx
  sessionAffinity: ClientIP
