apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jumpserver-redis
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    rollingUpdate:    # 滚动更新
      maxSurge: 25%   # 指定可以超过期望的pod数量的最大百分比，也可以是个数
      maxUnavailable: 25%    # 指定升级过程中不可用Pod的最大数量
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: jms-redis
        image: wojiushixiaobai/jms_redis:1.5.6
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        volumeMounts:
        - name: redis
          mountPath: /var/lib/redis
        env:
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_port
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_host
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jms-cfg
              key: redis_password
      volumes:
      - name: redis
        nfs:
          path: /data/redis
          server: 192.168.238.100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
  name: jumpserver-redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/name: redis
  sessionAffinity: ClientIP
